path = '/Users/suavemax27/scoutcloud/scoutcloud.dev/src/functions/sentiment-analyzer/handler.py'
with open(path, 'w') as f:
    f.write('#!/usr/bin/env python3\n')
    f.write('import boto3, json, logging, uuid\n')
    f.write('from datetime import datetime\n\n')
    f.write('logger = logging.getLogger()\n')
    f.write('logger.setLevel(logging.INFO)\n\n')
    f.write('def get_comprehend_client():\n')
    f.write('    return boto3.client("comprehend", region_name="us-east-1")\n\n')
    f.write('def get_dynamodb_resource():\n')
    f.write('    return boto3.resource("dynamodb", region_name="us-east-1")\n\n')
    f.write('def analyze_sentiment(text, comprehend=None):\n')
    f.write('    if comprehend is None:\n')
    f.write('        comprehend = get_comprehend_client()\n')
    f.write('    response = comprehend.detect_sentiment(\n')
    f.write('        Text=text,\n')
    f.write('        LanguageCode="en",\n')
    f.write('    )\n')
    f.write('    return {\n')
    f.write('        "sentiment": response["Sentiment"],\n')
    f.write('        "scores": {\n')
    f.write('            "positive": round(response["SentimentScore"]["Positive"], 4),\n')
    f.write('            "negative": round(response["SentimentScore"]["Negative"], 4),\n')
    f.write('            "neutral":  round(response["SentimentScore"]["Neutral"],  4),\n')
    f.write('            "mixed":    round(response["SentimentScore"]["Mixed"],    4),\n')
    f.write('        }\n')
    f.write('    }\n\n')
    f.write('def lambda_handler(event, context, comprehend=None, dynamodb=None):\n')
    f.write('    if dynamodb is None:\n')
    f.write('        dynamodb = get_dynamodb_resource()\n')
    f.write('    table = dynamodb.Table("scoutcloud-fan-sentiment")\n')
    f.write('    results = []\n')
    f.write('    for comment in event.get("comments", []):\n')
    f.write('        text    = comment.get("text", "")\n')
    f.write('        user_id = comment.get("user_id", "anonymous")\n')
    f.write('        if not text:\n')
    f.write('            continue\n')
    f.write('        analysis = analyze_sentiment(text, comprehend)\n')
    f.write('        comment_id = str(uuid.uuid4())\n')
    f.write('        table.put_item(Item={\n')
    f.write('            "comment_id":  comment_id,\n')
    f.write('            "user_id":     user_id,\n')
    f.write('            "text":        text[:500],\n')
    f.write('            "sentiment":   analysis["sentiment"],\n')
    f.write('            "scores":      analysis["scores"],\n')
    f.write('            "analyzed_at": datetime.utcnow().isoformat(),\n')
    f.write('        })\n')
    f.write('        logger.info(json.dumps({\n')
    f.write('            "event": "sentiment_analyzed",\n')
    f.write('            "comment_id": comment_id,\n')
    f.write('            "sentiment": analysis["sentiment"],\n')
    f.write('        }))\n')
    f.write('        results.append({"comment_id": comment_id, "sentiment": analysis["sentiment"]})\n')
    f.write('    return {"analyzed": len(results), "results": results}\n')
print("Done!")
