path = '/Users/suavemax27/scoutcloud/scoutcloud.dev/infra/modules/network/main.tf'
with open(path, 'w') as f:
    f.write('variable "vpc_cidr"    { default = "10.0.0.0/16" }\n')
    f.write('variable "project"     { default = "scoutcloud" }\n')
    f.write('variable "environment" { default = "dev" }\n\n')
    f.write('data "aws_availability_zones" "available" { state = "available" }\n\n')
    f.write('resource "aws_vpc" "main" {\n')
    f.write('  cidr_block           = var.vpc_cidr\n')
    f.write('  enable_dns_hostnames = true\n')
    f.write('  enable_dns_support   = true\n')
    f.write('  tags = { Name = "${var.project}-vpc", Project = var.project, Environment = var.environment }\n')
    f.write('}\n\n')
    f.write('resource "aws_internet_gateway" "main" {\n')
    f.write('  vpc_id = aws_vpc.main.id\n')
    f.write('  tags   = { Name = "${var.project}-igw", Project = var.project }\n')
    f.write('}\n\n')
    f.write('resource "aws_subnet" "public" {\n')
    f.write('  count                   = 2\n')
    f.write('  vpc_id                  = aws_vpc.main.id\n')
    f.write('  cidr_block              = cidrsubnet(var.vpc_cidr, 8, count.index)\n')
    f.write('  availability_zone       = data.aws_availability_zones.available.names[count.index]\n')
    f.write('  map_public_ip_on_launch = true\n')
    f.write('  tags = { Name = "${var.project}-public-${count.index + 1}", Tier = "public", Project = var.project }\n')
    f.write('}\n\n')
    f.write('resource "aws_subnet" "private" {\n')
    f.write('  count             = 2\n')
    f.write('  vpc_id            = aws_vpc.main.id\n')
    f.write('  cidr_block        = cidrsubnet(var.vpc_cidr, 8, count.index + 10)\n')
    f.write('  availability_zone = data.aws_availability_zones.available.names[count.index]\n')
    f.write('  tags = { Name = "${var.project}-private-${count.index + 1}", Tier = "private", Project = var.project }\n')
    f.write('}\n\n')
    f.write('resource "aws_subnet" "isolated" {\n')
    f.write('  count             = 2\n')
    f.write('  vpc_id            = aws_vpc.main.id\n')
    f.write('  cidr_block        = cidrsubnet(var.vpc_cidr, 8, count.index + 20)\n')
    f.write('  availability_zone = data.aws_availability_zones.available.names[count.index]\n')
    f.write('  tags = { Name = "${var.project}-isolated-${count.index + 1}", Tier = "isolated", Project = var.project }\n')
    f.write('}\n\n')
    f.write('resource "aws_eip" "nat" {\n')
    f.write('  domain     = "vpc"\n')
    f.write('  tags       = { Name = "${var.project}-nat-eip", Project = var.project }\n')
    f.write('  depends_on = [aws_internet_gateway.main]\n')
    f.write('}\n\n')
    f.write('resource "aws_nat_gateway" "main" {\n')
    f.write('  allocation_id = aws_eip.nat.id\n')
    f.write('  subnet_id     = aws_subnet.public[0].id\n')
    f.write('  tags          = { Name = "${var.project}-nat", Project = var.project }\n')
    f.write('  depends_on    = [aws_internet_gateway.main]\n')
    f.write('}\n\n')
    f.write('resource "aws_route_table" "public" {\n')
    f.write('  vpc_id = aws_vpc.main.id\n')
    f.write('  route {\n')
    f.write('    cidr_block = "0.0.0.0/0"\n')
    f.write('    gateway_id = aws_internet_gateway.main.id\n')
    f.write('  }\n')
    f.write('  tags = { Name = "${var.project}-public-rt", Project = var.project }\n')
    f.write('}\n\n')
    f.write('resource "aws_route_table" "private" {\n')
    f.write('  vpc_id = aws_vpc.main.id\n')
    f.write('  route {\n')
    f.write('    cidr_block     = "0.0.0.0/0"\n')
    f.write('    nat_gateway_id = aws_nat_gateway.main.id\n')
    f.write('  }\n')
    f.write('  tags = { Name = "${var.project}-private-rt", Project = var.project }\n')
    f.write('}\n\n')
    f.write('resource "aws_route_table" "isolated" {\n')
    f.write('  vpc_id = aws_vpc.main.id\n')
    f.write('  tags   = { Name = "${var.project}-isolated-rt", Project = var.project }\n')
    f.write('}\n\n')
    f.write('resource "aws_route_table_association" "public" {\n')
    f.write('  count          = 2\n')
    f.write('  subnet_id      = aws_subnet.public[count.index].id\n')
    f.write('  route_table_id = aws_route_table.public.id\n')
    f.write('}\n\n')
    f.write('resource "aws_route_table_association" "private" {\n')
    f.write('  count          = 2\n')
    f.write('  subnet_id      = aws_subnet.private[count.index].id\n')
    f.write('  route_table_id = aws_route_table.private.id\n')
    f.write('}\n\n')
    f.write('resource "aws_route_table_association" "isolated" {\n')
    f.write('  count          = 2\n')
    f.write('  subnet_id      = aws_subnet.isolated[count.index].id\n')
    f.write('  route_table_id = aws_route_table.isolated.id\n')
    f.write('}\n\n')
    f.write('resource "aws_cloudwatch_log_group" "flow_logs" {\n')
    f.write('  name              = "/aws/vpc/${var.project}-flow-logs"\n')
    f.write('  retention_in_days = 30\n')
    f.write('}\n\n')
    f.write('resource "aws_iam_role" "flow_logs" {\n')
    f.write('  name = "${var.project}-flow-logs-role"\n')
    f.write('  assume_role_policy = jsonencode({\n')
    f.write('    Version = "2012-10-17"\n')
    f.write('    Statement = [{ Effect = "Allow", Principal = { Service = "vpc-flow-logs.amazonaws.com" }, Action = "sts:AssumeRole" }]\n')
    f.write('  })\n')
    f.write('}\n\n')
    f.write('resource "aws_flow_log" "main" {\n')
    f.write('  vpc_id          = aws_vpc.main.id\n')
    f.write('  traffic_type    = "ALL"\n')
    f.write('  iam_role_arn    = aws_iam_role.flow_logs.arn\n')
    f.write('  log_destination = aws_cloudwatch_log_group.flow_logs.arn\n')
    f.write('}\n\n')
    f.write('output "vpc_id"              { value = aws_vpc.main.id }\n')
    f.write('output "public_subnet_ids"   { value = aws_subnet.public[*].id }\n')
    f.write('output "private_subnet_ids"  { value = aws_subnet.private[*].id }\n')
    f.write('output "isolated_subnet_ids" { value = aws_subnet.isolated[*].id }\n')
print("Done!")
