path = '/Users/suavemax27/scoutcloud/scoutcloud.dev/infra/cognito.tf'
with open(path, 'w') as f:
    f.write('resource "aws_cognito_user_pool" "main" {\n')
    f.write('  name = "scoutcloud-users"\n\n')
    f.write('  password_policy {\n')
    f.write('    minimum_length                   = 8\n')
    f.write('    require_uppercase                = true\n')
    f.write('    require_lowercase                = true\n')
    f.write('    require_numbers                  = true\n')
    f.write('    require_symbols                  = false\n')
    f.write('    temporary_password_validity_days = 7\n')
    f.write('  }\n\n')
    f.write('  auto_verified_attributes = ["email"]\n\n')
    f.write('  verification_message_template {\n')
    f.write('    default_email_option = "CONFIRM_WITH_CODE"\n')
    f.write('    email_subject        = "ScoutCloud - Verify your email"\n')
    f.write('    email_message        = "Your verification code is {####}"\n')
    f.write('  }\n\n')
    f.write('  schema {\n')
    f.write('    name                = "email"\n')
    f.write('    attribute_data_type = "String"\n')
    f.write('    required            = true\n')
    f.write('    mutable             = true\n')
    f.write('  }\n\n')
    f.write('  schema {\n')
    f.write('    name                = "subscription_tier"\n')
    f.write('    attribute_data_type = "String"\n')
    f.write('    required            = false\n')
    f.write('    mutable             = true\n')
    f.write('    string_attribute_constraints {\n')
    f.write('      min_length = 1\n')
    f.write('      max_length = 20\n')
    f.write('    }\n')
    f.write('  }\n\n')
    f.write('  tags = { Project = "scoutcloud" }\n')
    f.write('}\n\n')
    f.write('resource "aws_cognito_user_pool_client" "web" {\n')
    f.write('  name         = "scoutcloud-web"\n')
    f.write('  user_pool_id = aws_cognito_user_pool.main.id\n\n')
    f.write('  generate_secret                      = false\n')
    f.write('  allowed_oauth_flows                  = ["code"]\n')
    f.write('  allowed_oauth_flows_user_pool_client = true\n')
    f.write('  allowed_oauth_scopes                 = ["email", "openid", "profile"]\n\n')
    f.write('  callback_urls = [\n')
    f.write('    "https://app.scoutcloud.dev",\n')
    f.write('    "http://localhost:8080",\n')
    f.write('  ]\n\n')
    f.write('  logout_urls = [\n')
    f.write('    "https://app.scoutcloud.dev",\n')
    f.write('    "http://localhost:8080",\n')
    f.write('  ]\n\n')
    f.write('  supported_identity_providers = ["COGNITO"]\n\n')
    f.write('  explicit_auth_flows = [\n')
    f.write('    "ALLOW_REFRESH_TOKEN_AUTH",\n')
    f.write('    "ALLOW_USER_PASSWORD_AUTH",\n')
    f.write('    "ALLOW_USER_SRP_AUTH",\n')
    f.write('  ]\n\n')
    f.write('  access_token_validity  = 1\n')
    f.write('  id_token_validity      = 1\n')
    f.write('  refresh_token_validity = 30\n\n')
    f.write('  token_validity_units {\n')
    f.write('    access_token  = "hours"\n')
    f.write('    id_token      = "hours"\n')
    f.write('    refresh_token = "days"\n')
    f.write('  }\n')
    f.write('}\n\n')
    f.write('resource "aws_cognito_user_pool_domain" "main" {\n')
    f.write('  domain       = "scoutcloud-auth"\n')
    f.write('  user_pool_id = aws_cognito_user_pool.main.id\n')
    f.write('}\n\n')
    f.write('resource "aws_apigatewayv2_api" "main" {\n')
    f.write('  name          = "scoutcloud-api"\n')
    f.write('  protocol_type = "HTTP"\n')
    f.write('  tags          = { Project = "scoutcloud" }\n')
    f.write('}\n\n')
    f.write('resource "aws_apigatewayv2_authorizer" "cognito" {\n')
    f.write('  api_id           = aws_apigatewayv2_api.main.id\n')
    f.write('  authorizer_type  = "JWT"\n')
    f.write('  name             = "cognito-authorizer"\n')
    f.write('  identity_sources = ["$request.header.Authorization"]\n\n')
    f.write('  jwt_configuration {\n')
    f.write('    audience = [aws_cognito_user_pool_client.web.id]\n')
    f.write('    issuer   = "https://cognito-idp.us-east-1.amazonaws.com/${aws_cognito_user_pool.main.id}"\n')
    f.write('  }\n')
    f.write('}\n\n')
    f.write('output "cognito_user_pool_id"     { value = aws_cognito_user_pool.main.id }\n')
    f.write('output "cognito_client_id"        { value = aws_cognito_user_pool_client.web.id }\n')
    f.write('output "cognito_hosted_ui_domain" { value = aws_cognito_user_pool_domain.main.domain }\n')
print("Done!")
