path = '/Users/suavemax27/scoutcloud/scoutcloud.dev/infra/eks.tf'
with open(path, 'w') as f:
    f.write('resource "aws_iam_role" "eks" {\n')
    f.write('  name = "scoutcloud-eks-cluster-role"\n')
    f.write('  assume_role_policy = jsonencode({\n')
    f.write('    Version = "2012-10-17"\n')
    f.write('    Statement = [{ Effect = "Allow", Principal = { Service = "eks.amazonaws.com" }, Action = "sts:AssumeRole" }]\n')
    f.write('  })\n')
    f.write('}\n\n')
    f.write('resource "aws_iam_role_policy_attachment" "eks_cluster" {\n')
    f.write('  role       = aws_iam_role.eks.name\n')
    f.write('  policy_arn = "arn:aws:iam::aws:policy/AmazonEKSClusterPolicy"\n')
    f.write('}\n\n')
    f.write('resource "aws_iam_role" "eks_nodes" {\n')
    f.write('  name = "scoutcloud-eks-nodes-role"\n')
    f.write('  assume_role_policy = jsonencode({\n')
    f.write('    Version = "2012-10-17"\n')
    f.write('    Statement = [{ Effect = "Allow", Principal = { Service = "ec2.amazonaws.com" }, Action = "sts:AssumeRole" }]\n')
    f.write('  })\n')
    f.write('}\n\n')
    f.write('resource "aws_iam_role_policy_attachment" "eks_worker_node" {\n')
    f.write('  role       = aws_iam_role.eks_nodes.name\n')
    f.write('  policy_arn = "arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy"\n')
    f.write('}\n\n')
    f.write('resource "aws_iam_role_policy_attachment" "eks_cni" {\n')
    f.write('  role       = aws_iam_role.eks_nodes.name\n')
    f.write('  policy_arn = "arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy"\n')
    f.write('}\n\n')
    f.write('resource "aws_iam_role_policy_attachment" "eks_container_registry" {\n')
    f.write('  role       = aws_iam_role.eks_nodes.name\n')
    f.write('  policy_arn = "arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly"\n')
    f.write('}\n\n')
    f.write('resource "aws_eks_cluster" "main" {\n')
    f.write('  name     = "scoutcloud"\n')
    f.write('  role_arn = aws_iam_role.eks.arn\n')
    f.write('  version  = "1.29"\n\n')
    f.write('  vpc_config {\n')
    f.write('    subnet_ids              = module.network.private_subnet_ids\n')
    f.write('    endpoint_private_access = true\n')
    f.write('    endpoint_public_access  = true\n')
    f.write('  }\n\n')
    f.write('  tags       = local.common_tags\n')
    f.write('  depends_on = [aws_iam_role_policy_attachment.eks_cluster]\n')
    f.write('}\n\n')
    f.write('resource "aws_eks_node_group" "main" {\n')
    f.write('  cluster_name    = aws_eks_cluster.main.name\n')
    f.write('  node_group_name = "scoutcloud-nodes"\n')
    f.write('  node_role_arn   = aws_iam_role.eks_nodes.arn\n')
    f.write('  subnet_ids      = module.network.private_subnet_ids\n\n')
    f.write('  scaling_config {\n')
    f.write('    desired_size = 2\n')
    f.write('    min_size     = 1\n')
    f.write('    max_size     = 4\n')
    f.write('  }\n\n')
    f.write('  instance_types = ["t3.small"]\n')
    f.write('  tags           = local.common_tags\n\n')
    f.write('  depends_on = [\n')
    f.write('    aws_iam_role_policy_attachment.eks_worker_node,\n')
    f.write('    aws_iam_role_policy_attachment.eks_cni,\n')
    f.write('    aws_iam_role_policy_attachment.eks_container_registry,\n')
    f.write('  ]\n')
    f.write('}\n\n')
    f.write('output "eks_cluster_name" { value = aws_eks_cluster.main.name }\n')
print("Done!")
