path = '/Users/suavemax27/scoutcloud/scoutcloud.dev/infra/fis.tf'
with open(path, 'w') as f:
    f.write('resource "aws_iam_role" "fis" {\n')
    f.write('  name = "scoutcloud-fis-role"\n')
    f.write('  assume_role_policy = jsonencode({\n')
    f.write('    Version = "2012-10-17"\n')
    f.write('    Statement = [{ Effect = "Allow", Principal = { Service = "fis.amazonaws.com" }, Action = "sts:AssumeRole" }]\n')
    f.write('  })\n')
    f.write('}\n\n')
    f.write('resource "aws_iam_role_policy" "fis" {\n')
    f.write('  name = "fis-policy"\n')
    f.write('  role = aws_iam_role.fis.id\n')
    f.write('  policy = jsonencode({\n')
    f.write('    Version = "2012-10-17"\n')
    f.write('    Statement = [{\n')
    f.write('      Effect = "Allow"\n')
    f.write('      Action = ["ec2:TerminateInstances", "ec2:DescribeInstances", "autoscaling:DescribeAutoScalingGroups"]\n')
    f.write('      Resource = "*"\n')
    f.write('    }]\n')
    f.write('  })\n')
    f.write('}\n\n')
    f.write('resource "aws_fis_experiment_template" "terminate_instance" {\n')
    f.write('  description = "Terminate one ASG instance - verify ASG replaces it"\n')
    f.write('  role_arn    = aws_iam_role.fis.arn\n\n')
    f.write('  action {\n')
    f.write('    name      = "terminate-instance"\n')
    f.write('    action_id = "aws:ec2:terminate-instances"\n')
    f.write('    target {\n')
    f.write('      key   = "Instances"\n')
    f.write('      value = "one-instance"\n')
    f.write('    }\n')
    f.write('  }\n\n')
    f.write('  target {\n')
    f.write('    name           = "one-instance"\n')
    f.write('    resource_type  = "aws:ec2:instance"\n')
    f.write('    selection_mode = "COUNT(1)"\n')
    f.write('    resource_tag {\n')
    f.write('      key   = "aws:autoscaling:groupName"\n')
    f.write('      value = "scoutcloud-asg"\n')
    f.write('    }\n')
    f.write('  }\n\n')
    f.write('  stop_condition {\n')
    f.write('    source = "none"\n')
    f.write('  }\n\n')
    f.write('  tags = local.common_tags\n')
    f.write('}\n\n')
    f.write('output "fis_template_id" { value = aws_fis_experiment_template.terminate_instance.id }\n')
print("Done!")
