path = '/Users/suavemax27/scoutcloud/scoutcloud.dev/infra/finops.tf'
with open(path, 'w') as f:
    f.write('# AWS Config for tag compliance\n')
    f.write('resource "aws_iam_role" "config" {\n')
    f.write('  name = "scoutcloud-config-role"\n')
    f.write('  assume_role_policy = jsonencode({\n')
    f.write('    Version = "2012-10-17"\n')
    f.write('    Statement = [{ Effect = "Allow", Principal = { Service = "config.amazonaws.com" }, Action = "sts:AssumeRole" }]\n')
    f.write('  })\n')
    f.write('}\n\n')
    f.write('resource "aws_iam_role_policy_attachment" "config" {\n')
    f.write('  role       = aws_iam_role.config.name\n')
    f.write('  policy_arn = "arn:aws:iam::aws:policy/service-role/AWSConfigRole"\n')
    f.write('}\n\n')
    f.write('resource "aws_config_configuration_recorder" "main" {\n')
    f.write('  name     = "scoutcloud-config"\n')
    f.write('  role_arn = aws_iam_role.config.arn\n')
    f.write('  recording_group {\n')
    f.write('    all_supported = true\n')
    f.write('  }\n')
    f.write('}\n\n')
    f.write('resource "aws_config_delivery_channel" "main" {\n')
    f.write('  name           = "scoutcloud-config"\n')
    f.write('  s3_bucket_name = aws_s3_bucket.assets.bucket\n')
    f.write('  s3_key_prefix  = "config"\n')
    f.write('  depends_on     = [aws_config_configuration_recorder.main]\n')
    f.write('}\n\n')
    f.write('resource "aws_config_configuration_recorder_status" "main" {\n')
    f.write('  name       = aws_config_configuration_recorder.main.name\n')
    f.write('  is_enabled = true\n')
    f.write('  depends_on = [aws_config_delivery_channel.main]\n')
    f.write('}\n\n')
    f.write('resource "aws_config_config_rule" "required_tags" {\n')
    f.write('  name = "scoutcloud-required-tags"\n')
    f.write('  source {\n')
    f.write('    owner             = "AWS"\n')
    f.write('    source_identifier = "REQUIRED_TAGS"\n')
    f.write('  }\n')
    f.write('  input_parameters = jsonencode({\n')
    f.write('    tag1Key = "Project"\n')
    f.write('    tag2Key = "Environment"\n')
    f.write('    tag3Key = "Owner"\n')
    f.write('  })\n')
    f.write('  depends_on = [aws_config_configuration_recorder_status.main]\n')
    f.write('  tags = { Project = "scoutcloud" }\n')
    f.write('}\n\n')
    f.write('# Budget alarms\n')
    f.write('resource "aws_budgets_budget" "monthly" {\n')
    f.write('  name         = "scoutcloud-monthly-budget"\n')
    f.write('  budget_type  = "COST"\n')
    f.write('  limit_amount = "50"\n')
    f.write('  limit_unit   = "USD"\n')
    f.write('  time_unit    = "MONTHLY"\n\n')
    f.write('  notification {\n')
    f.write('    comparison_operator        = "GREATER_THAN"\n')
    f.write('    threshold                  = 80\n')
    f.write('    threshold_type             = "PERCENTAGE"\n')
    f.write('    notification_type          = "ACTUAL"\n')
    f.write('    subscriber_email_addresses = ["marcus@scoutcloud.dev"]\n')
    f.write('  }\n\n')
    f.write('  notification {\n')
    f.write('    comparison_operator        = "GREATER_THAN"\n')
    f.write('    threshold                  = 100\n')
    f.write('    threshold_type             = "PERCENTAGE"\n')
    f.write('    notification_type          = "FORECASTED"\n')
    f.write('    subscriber_email_addresses = ["marcus@scoutcloud.dev"]\n')
    f.write('  }\n')
    f.write('}\n\n')
    f.write('resource "aws_budgets_budget" "eks" {\n')
    f.write('  name         = "scoutcloud-eks-budget"\n')
    f.write('  budget_type  = "COST"\n')
    f.write('  limit_amount = "10"\n')
    f.write('  limit_unit   = "USD"\n')
    f.write('  time_unit    = "DAILY"\n\n')
    f.write('  cost_filter {\n')
    f.write('    name   = "Service"\n')
    f.write('    values = ["Amazon Elastic Kubernetes Service"]\n')
    f.write('  }\n\n')
    f.write('  notification {\n')
    f.write('    comparison_operator        = "GREATER_THAN"\n')
    f.write('    threshold                  = 100\n')
    f.write('    threshold_type             = "PERCENTAGE"\n')
    f.write('    notification_type          = "ACTUAL"\n')
    f.write('    subscriber_email_addresses = ["marcus@scoutcloud.dev"]\n')
    f.write('  }\n')
    f.write('}\n\n')
    f.write('# Cost cleanup Lambda\n')
    f.write('data "archive_file" "cost_cleanup" {\n')
    f.write('  type        = "zip"\n')
    f.write('  source_dir  = "../src/functions/cost-cleanup"\n')
    f.write('  output_path = "/tmp/cost-cleanup.zip"\n')
    f.write('}\n\n')
    f.write('resource "aws_lambda_function" "cost_cleanup" {\n')
    f.write('  filename         = data.archive_file.cost_cleanup.output_path\n')
    f.write('  function_name    = "scoutcloud-cost-cleanup"\n')
    f.write('  role             = aws_iam_role.lambda.arn\n')
    f.write('  handler          = "handler.lambda_handler"\n')
    f.write('  runtime          = "python3.11"\n')
    f.write('  source_code_hash = data.archive_file.cost_cleanup.output_base64sha256\n')
    f.write('  timeout          = 60\n')
    f.write('  tags             = local.common_tags\n')
    f.write('}\n\n')
    f.write('resource "aws_cloudwatch_event_rule" "stop_dev" {\n')
    f.write('  name                = "stop-dev-instances"\n')
    f.write('  schedule_expression = "cron(0 0 ? * MON-FRI *)"\n')
    f.write('}\n\n')
    f.write('resource "aws_cloudwatch_event_target" "stop_dev" {\n')
    f.write('  rule      = aws_cloudwatch_event_rule.stop_dev.name\n')
    f.write('  target_id = "StopDevInstances"\n')
    f.write('  arn       = aws_lambda_function.cost_cleanup.arn\n')
    f.write('  input     = jsonencode({"action": "stop"})\n')
    f.write('}\n\n')
    f.write('resource "aws_cloudwatch_event_rule" "start_dev" {\n')
    f.write('  name                = "start-dev-instances"\n')
    f.write('  schedule_expression = "cron(0 13 ? * MON-FRI *)"\n')
    f.write('}\n\n')
    f.write('resource "aws_cloudwatch_event_target" "start_dev" {\n')
    f.write('  rule      = aws_cloudwatch_event_rule.start_dev.name\n')
    f.write('  target_id = "StartDevInstances"\n')
    f.write('  arn       = aws_lambda_function.cost_cleanup.arn\n')
    f.write('  input     = jsonencode({"action": "start"})\n')
    f.write('}\n\n')
    f.write('resource "aws_lambda_permission" "stop_dev" {\n')
    f.write('  statement_id  = "AllowEventBridgeStop"\n')
    f.write('  action        = "lambda:InvokeFunction"\n')
    f.write('  function_name = aws_lambda_function.cost_cleanup.function_name\n')
    f.write('  principal     = "events.amazonaws.com"\n')
    f.write('  source_arn    = aws_cloudwatch_event_rule.stop_dev.arn\n')
    f.write('}\n\n')
    f.write('resource "aws_lambda_permission" "start_dev" {\n')
    f.write('  statement_id  = "AllowEventBridgeStart"\n')
    f.write('  action        = "lambda:InvokeFunction"\n')
    f.write('  function_name = aws_lambda_function.cost_cleanup.function_name\n')
    f.write('  principal     = "events.amazonaws.com"\n')
    f.write('  source_arn    = aws_cloudwatch_event_rule.start_dev.arn\n')
    f.write('}\n')
print("Done!")
