path = '/Users/suavemax27/scoutcloud/scoutcloud.dev/infra/backup.tf'
with open(path, 'w') as f:
    f.write('resource "aws_backup_vault" "main" {\n')
    f.write('  name        = "scoutcloud-backups"\n')
    f.write('  kms_key_arn = aws_kms_key.rds.arn\n')
    f.write('  tags        = local.common_tags\n')
    f.write('}\n\n')
    f.write('resource "aws_backup_plan" "main" {\n')
    f.write('  name = "scoutcloud-backup-plan"\n\n')
    f.write('  rule {\n')
    f.write('    rule_name         = "daily-backup"\n')
    f.write('    target_vault_name = aws_backup_vault.main.name\n')
    f.write('    schedule          = "cron(0 5 ? * * *)"\n\n')
    f.write('    lifecycle {\n')
    f.write('      delete_after = 30\n')
    f.write('    }\n\n')
    f.write('    copy_action {\n')
    f.write('      lifecycle { delete_after = 7 }\n')
    f.write('      destination_vault_arn = "arn:aws:backup:us-west-2:${data.aws_caller_identity.current.account_id}:backup-vault:Default"\n')
    f.write('    }\n')
    f.write('  }\n\n')
    f.write('  tags = local.common_tags\n')
    f.write('}\n\n')
    f.write('data "aws_caller_identity" "current" {}\n\n')
    f.write('resource "aws_backup_selection" "main" {\n')
    f.write('  name         = "scoutcloud-resources"\n')
    f.write('  plan_id      = aws_backup_plan.main.id\n')
    f.write('  iam_role_arn = aws_iam_role.backup.arn\n\n')
    f.write('  selection_tag {\n')
    f.write('    type  = "STRINGEQUALS"\n')
    f.write('    key   = "Project"\n')
    f.write('    value = "scoutcloud"\n')
    f.write('  }\n')
    f.write('}\n\n')
    f.write('resource "aws_iam_role" "backup" {\n')
    f.write('  name = "scoutcloud-backup-role"\n')
    f.write('  assume_role_policy = jsonencode({\n')
    f.write('    Version = "2012-10-17"\n')
    f.write('    Statement = [{ Effect = "Allow", Principal = { Service = "backup.amazonaws.com" }, Action = "sts:AssumeRole" }]\n')
    f.write('  })\n')
    f.write('}\n\n')
    f.write('resource "aws_iam_role_policy_attachment" "backup" {\n')
    f.write('  role       = aws_iam_role.backup.name\n')
    f.write('  policy_arn = "arn:aws:iam::aws:policy/service-role/AWSBackupServiceRolePolicyForBackup"\n')
    f.write('}\n\n')
    f.write('output "backup_role_arn" { value = aws_iam_role.backup.arn }\n')
print("Done!")
