path = '/Users/suavemax27/scoutcloud/scoutcloud.dev/infra/ai.tf'
with open(path, 'w') as f:
    f.write('data "archive_file" "photo_tagger" {\n')
    f.write('  type        = "zip"\n')
    f.write('  source_dir  = "../src/functions/photo-tagger"\n')
    f.write('  output_path = "/tmp/photo-tagger.zip"\n')
    f.write('}\n\n')
    f.write('data "archive_file" "sentiment_analyzer" {\n')
    f.write('  type        = "zip"\n')
    f.write('  source_dir  = "../src/functions/sentiment-analyzer"\n')
    f.write('  output_path = "/tmp/sentiment-analyzer.zip"\n')
    f.write('}\n\n')
    f.write('resource "aws_dynamodb_table" "photo_tags" {\n')
    f.write('  name         = "scoutcloud-photo-tags"\n')
    f.write('  billing_mode = "PAY_PER_REQUEST"\n')
    f.write('  hash_key     = "photo_key"\n')
    f.write('  attribute {\n')
    f.write('    name = "photo_key"\n')
    f.write('    type = "S"\n')
    f.write('  }\n')
    f.write('  tags = { Name = "scoutcloud-photo-tags", Project = "scoutcloud" }\n')
    f.write('}\n\n')
    f.write('resource "aws_dynamodb_table" "sentiment" {\n')
    f.write('  name         = "scoutcloud-fan-sentiment"\n')
    f.write('  billing_mode = "PAY_PER_REQUEST"\n')
    f.write('  hash_key     = "comment_id"\n')
    f.write('  attribute {\n')
    f.write('    name = "comment_id"\n')
    f.write('    type = "S"\n')
    f.write('  }\n')
    f.write('  tags = { Name = "scoutcloud-fan-sentiment", Project = "scoutcloud" }\n')
    f.write('}\n\n')
    f.write('resource "aws_iam_role" "ai_lambda" {\n')
    f.write('  name = "scoutcloud-ai-lambda-role"\n')
    f.write('  assume_role_policy = jsonencode({\n')
    f.write('    Version = "2012-10-17"\n')
    f.write('    Statement = [{ Effect = "Allow", Principal = { Service = "lambda.amazonaws.com" }, Action = "sts:AssumeRole" }]\n')
    f.write('  })\n')
    f.write('}\n\n')
    f.write('resource "aws_iam_role_policy" "ai_lambda" {\n')
    f.write('  name = "ai-lambda-policy"\n')
    f.write('  role = aws_iam_role.ai_lambda.id\n')
    f.write('  policy = jsonencode({\n')
    f.write('    Version = "2012-10-17"\n')
    f.write('    Statement = [\n')
    f.write('      { Effect = "Allow", Action = ["rekognition:DetectLabels", "rekognition:DetectFaces"], Resource = "*" },\n')
    f.write('      { Effect = "Allow", Action = ["comprehend:DetectSentiment", "comprehend:DetectEntities"], Resource = "*" },\n')
    f.write('      { Effect = "Allow", Action = ["dynamodb:PutItem", "dynamodb:GetItem"], Resource = [aws_dynamodb_table.photo_tags.arn, aws_dynamodb_table.sentiment.arn] },\n')
    f.write('      { Effect = "Allow", Action = ["s3:GetObject"], Resource = "${aws_s3_bucket.assets.arn}/*" },\n')
    f.write('      { Effect = "Allow", Action = ["logs:CreateLogGroup", "logs:CreateLogStream", "logs:PutLogEvents"], Resource = "arn:aws:logs:*:*:*" }\n')
    f.write('    ]\n')
    f.write('  })\n')
    f.write('}\n\n')
    f.write('resource "aws_lambda_function" "photo_tagger" {\n')
    f.write('  filename         = data.archive_file.photo_tagger.output_path\n')
    f.write('  function_name    = "scoutcloud-photo-tagger"\n')
    f.write('  role             = aws_iam_role.ai_lambda.arn\n')
    f.write('  handler          = "handler.lambda_handler"\n')
    f.write('  runtime          = "python3.11"\n')
    f.write('  source_code_hash = data.archive_file.photo_tagger.output_base64sha256\n')
    f.write('  timeout          = 60\n')
    f.write('  tags             = { Project = "scoutcloud" }\n')
    f.write('}\n\n')
    f.write('resource "aws_lambda_function" "sentiment_analyzer" {\n')
    f.write('  filename         = data.archive_file.sentiment_analyzer.output_path\n')
    f.write('  function_name    = "scoutcloud-sentiment-analyzer"\n')
    f.write('  role             = aws_iam_role.ai_lambda.arn\n')
    f.write('  handler          = "handler.lambda_handler"\n')
    f.write('  runtime          = "python3.11"\n')
    f.write('  source_code_hash = data.archive_file.sentiment_analyzer.output_base64sha256\n')
    f.write('  timeout          = 60\n')
    f.write('  tags             = { Project = "scoutcloud" }\n')
    f.write('}\n\n')
    f.write('resource "aws_lambda_permission" "photo_tagger_s3" {\n')
    f.write('  statement_id  = "AllowS3Invoke"\n')
    f.write('  action        = "lambda:InvokeFunction"\n')
    f.write('  function_name = aws_lambda_function.photo_tagger.function_name\n')
    f.write('  principal     = "s3.amazonaws.com"\n')
    f.write('  source_arn    = aws_s3_bucket.assets.arn\n')
    f.write('}\n\n')
    f.write('resource "aws_s3_bucket_notification" "photo_tagger" {\n')
    f.write('  bucket = aws_s3_bucket.assets.id\n')
    f.write('  lambda_function {\n')
    f.write('    lambda_function_arn = aws_lambda_function.photo_tagger.arn\n')
    f.write('    events              = ["s3:ObjectCreated:*"]\n')
    f.write('    filter_prefix       = "players/photos/"\n')
    f.write('    filter_suffix       = ".jpg"\n')
    f.write('  }\n')
    f.write('  depends_on = [aws_lambda_permission.photo_tagger_s3]\n')
    f.write('}\n')
print("Done!")
