path = '/Users/suavemax27/scoutcloud/scoutcloud.dev/infra/security.tf'
with open(path, 'w') as f:
    f.write('resource "aws_guardduty_detector" "main" {\n')
    f.write('  enable = true\n')
    f.write('  datasources {\n')
    f.write('    s3_logs { enable = true }\n')
    f.write('    kubernetes { audit_logs { enable = false } }\n')
    f.write('    malware_protection {\n')
    f.write('      scan_ec2_instance_with_findings { ebs_volumes { enable = true } }\n')
    f.write('    }\n')
    f.write('  }\n')
    f.write('  tags = { Project = "scoutcloud" }\n')
    f.write('}\n\n')
    f.write('resource "aws_wafv2_web_acl" "main" {\n')
    f.write('  name     = "scoutcloud-waf"\n')
    f.write('  scope    = "CLOUDFRONT"\n')
    f.write('  provider = aws.us_east_1\n\n')
    f.write('  default_action { allow {} }\n\n')
    f.write('  rule {\n')
    f.write('    name     = "AWS-CommonRuleSet"\n')
    f.write('    priority = 1\n')
    f.write('    override_action { none {} }\n')
    f.write('    statement {\n')
    f.write('      managed_rule_group_statement {\n')
    f.write('        vendor_name = "AWS"\n')
    f.write('        name        = "AWSManagedRulesCommonRuleSet"\n')
    f.write('      }\n')
    f.write('    }\n')
    f.write('    visibility_config {\n')
    f.write('      cloudwatch_metrics_enabled = true\n')
    f.write('      metric_name                = "CommonRuleSet"\n')
    f.write('      sampled_requests_enabled   = true\n')
    f.write('    }\n')
    f.write('  }\n\n')
    f.write('  rule {\n')
    f.write('    name     = "RateLimit"\n')
    f.write('    priority = 2\n')
    f.write('    action { block {} }\n')
    f.write('    statement {\n')
    f.write('      rate_based_statement {\n')
    f.write('        limit              = 1000\n')
    f.write('        aggregate_key_type = "IP"\n')
    f.write('      }\n')
    f.write('    }\n')
    f.write('    visibility_config {\n')
    f.write('      cloudwatch_metrics_enabled = true\n')
    f.write('      metric_name                = "RateLimit"\n')
    f.write('      sampled_requests_enabled   = true\n')
    f.write('    }\n')
    f.write('  }\n\n')
    f.write('  visibility_config {\n')
    f.write('    cloudwatch_metrics_enabled = true\n')
    f.write('    metric_name                = "scoutcloud-waf"\n')
    f.write('    sampled_requests_enabled   = true\n')
    f.write('  }\n\n')
    f.write('  tags = { Project = "scoutcloud" }\n')
    f.write('}\n\n')
    f.write('resource "aws_kms_key" "rds" {\n')
    f.write('  description             = "ScoutCloud RDS encryption key"\n')
    f.write('  deletion_window_in_days = 7\n')
    f.write('  enable_key_rotation     = true\n')
    f.write('  tags = { Name = "scoutcloud-rds-key", Project = "scoutcloud" }\n')
    f.write('}\n\n')
    f.write('resource "aws_kms_alias" "rds" {\n')
    f.write('  name          = "alias/scoutcloud-rds"\n')
    f.write('  target_key_id = aws_kms_key.rds.key_id\n')
    f.write('}\n\n')
    f.write('resource "aws_secretsmanager_secret" "rds_password" {\n')
    f.write('  name                    = "scoutcloud/rds/password"\n')
    f.write('  recovery_window_in_days = 7\n')
    f.write('  kms_key_id              = aws_kms_key.rds.arn\n')
    f.write('  tags = { Project = "scoutcloud" }\n')
    f.write('}\n\n')
    f.write('resource "aws_secretsmanager_secret_version" "rds_password" {\n')
    f.write('  secret_id     = aws_secretsmanager_secret.rds_password.id\n')
    f.write('  secret_string = jsonencode({\n')
    f.write('    username = "scoutadmin"\n')
    f.write('    password = var.db_password\n')
    f.write('  })\n')
    f.write('}\n\n')
    f.write('resource "aws_security_group" "vault" {\n')
    f.write('  name   = "scoutcloud-vault-sg"\n')
    f.write('  vpc_id = module.network.vpc_id\n')
    f.write('  ingress {\n')
    f.write('    from_port       = 8200\n')
    f.write('    to_port         = 8200\n')
    f.write('    protocol        = "tcp"\n')
    f.write('    security_groups = [aws_security_group.web.id]\n')
    f.write('  }\n')
    f.write('  egress {\n')
    f.write('    from_port   = 0\n')
    f.write('    to_port     = 0\n')
    f.write('    protocol    = "-1"\n')
    f.write('    cidr_blocks = ["0.0.0.0/0"]\n')
    f.write('  }\n')
    f.write('}\n\n')
    f.write('resource "aws_iam_role" "vault" {\n')
    f.write('  name = "scoutcloud-vault-role"\n')
    f.write('  assume_role_policy = jsonencode({\n')
    f.write('    Version = "2012-10-17"\n')
    f.write('    Statement = [{ Effect = "Allow", Principal = { Service = "ec2.amazonaws.com" }, Action = "sts:AssumeRole" }]\n')
    f.write('  })\n')
    f.write('}\n\n')
    f.write('resource "aws_iam_role_policy_attachment" "vault_ssm" {\n')
    f.write('  role       = aws_iam_role.vault.name\n')
    f.write('  policy_arn = "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore"\n')
    f.write('}\n\n')
    f.write('resource "aws_iam_instance_profile" "vault" {\n')
    f.write('  name = "scoutcloud-vault-profile"\n')
    f.write('  role = aws_iam_role.vault.name\n')
    f.write('}\n\n')
    f.write('resource "aws_instance" "vault" {\n')
    f.write('  ami                    = data.aws_ami.amazon_linux_2023.id\n')
    f.write('  instance_type          = "t3.micro"\n')
    f.write('  subnet_id              = module.network.private_subnet_ids[0]\n')
    f.write('  iam_instance_profile   = aws_iam_instance_profile.vault.name\n')
    f.write('  vpc_security_group_ids = [aws_security_group.vault.id]\n')
    f.write('  user_data = <<-EOF\n')
    f.write('    #!/bin/bash\n')
    f.write('    yum update -y\n')
    f.write('    yum install -y docker\n')
    f.write('    systemctl start docker\n')
    f.write('    systemctl enable docker\n')
    f.write('    docker run -d --name vault --cap-add=IPC_LOCK \\\n')
    f.write('      -p 8200:8200 \\\n')
    f.write('      -e VAULT_DEV_ROOT_TOKEN_ID=scoutcloud-vault-token \\\n')
    f.write('      -e VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200 \\\n')
    f.write('      hashicorp/vault:latest server -dev\n')
    f.write('  EOF\n')
    f.write('  tags = { Name = "scoutcloud-vault", Project = "scoutcloud" }\n')
    f.write('}\n\n')
    f.write('output "vault_instance_id" { value = aws_instance.vault.id }\n')
print("Done!")
