path = '/Users/suavemax27/scoutcloud/scoutcloud.dev/src/functions/photo-tagger/test_handler.py'
with open(path, 'w') as f:
    f.write('#!/usr/bin/env python3\n')
    f.write('import json, unittest\n')
    f.write('from unittest.mock import MagicMock, patch\n')
    f.write('from handler import analyze_photo, store_results, lambda_handler\n\n')
    f.write('class TestPhotoTagger(unittest.TestCase):\n\n')
    f.write('    def test_analyze_photo_returns_labels(self):\n')
    f.write('        mock_rekognition = MagicMock()\n')
    f.write('        mock_rekognition.detect_labels.return_value = {\n')
    f.write('            "Labels": [\n')
    f.write('                {"Name": "Basketball", "Confidence": 98.5},\n')
    f.write('                {"Name": "Person",     "Confidence": 96.2},\n')
    f.write('                {"Name": "Sports",     "Confidence": 94.1},\n')
    f.write('            ]\n')
    f.write('        }\n')
    f.write('        mock_rekognition.detect_faces.return_value = {\n')
    f.write('            "FaceDetails": [{"Confidence": 99.9}]\n')
    f.write('        }\n')
    f.write('        result = analyze_photo("scoutcloud-assets", "players/photos/jokic.jpg",\n')
    f.write('                               rekognition=mock_rekognition)\n')
    f.write('        self.assertEqual(len(result["labels"]), 3)\n')
    f.write('        self.assertEqual(result["face_count"], 1)\n')
    f.write('        self.assertTrue(result["is_basketball_photo"])\n')
    f.write('        mock_rekognition.detect_labels.assert_called_once_with(\n')
    f.write('            Image={"S3Object": {"Bucket": "scoutcloud-assets", "Name": "players/photos/jokic.jpg"}},\n')
    f.write('            MaxLabels=10,\n')
    f.write('            MinConfidence=80.0,\n')
    f.write('        )\n\n')
    f.write('    def test_non_photo_files_are_skipped(self):\n')
    f.write('        mock_rekognition = MagicMock()\n')
    f.write('        mock_dynamodb = MagicMock()\n')
    f.write('        event = {\n')
    f.write('            "Records": [{\n')
    f.write('                "s3": {\n')
    f.write('                    "bucket": {"name": "scoutcloud-assets"},\n')
    f.write('                    "object": {"key": "static/index.html"},\n')
    f.write('                }\n')
    f.write('            }]\n')
    f.write('        }\n')
    f.write('        result = lambda_handler(event, None,\n')
    f.write('                                rekognition=mock_rekognition,\n')
    f.write('                                dynamodb=mock_dynamodb)\n')
    f.write('        self.assertEqual(result["processed"], 0)\n')
    f.write('        mock_rekognition.detect_labels.assert_not_called()\n\n')
    f.write('    def test_full_handler_processes_photo(self):\n')
    f.write('        mock_rekognition = MagicMock()\n')
    f.write('        mock_rekognition.detect_labels.return_value = {\n')
    f.write('            "Labels": [{"Name": "Basketball", "Confidence": 99.0}]\n')
    f.write('        }\n')
    f.write('        mock_rekognition.detect_faces.return_value = {\n')
    f.write('            "FaceDetails": [{"Confidence": 99.0}]\n')
    f.write('        }\n')
    f.write('        mock_dynamodb = MagicMock()\n')
    f.write('        mock_table = MagicMock()\n')
    f.write('        mock_dynamodb.Table.return_value = mock_table\n')
    f.write('        event = {\n')
    f.write('            "Records": [{\n')
    f.write('                "s3": {\n')
    f.write('                    "bucket": {"name": "scoutcloud-assets"},\n')
    f.write('                    "object": {"key": "players/photos/curry.jpg"},\n')
    f.write('                }\n')
    f.write('            }]\n')
    f.write('        }\n')
    f.write('        result = lambda_handler(event, None,\n')
    f.write('                                rekognition=mock_rekognition,\n')
    f.write('                                dynamodb=mock_dynamodb)\n')
    f.write('        self.assertEqual(result["processed"], 1)\n')
    f.write('        mock_table.put_item.assert_called_once()\n\n')
    f.write('if __name__ == "__main__":\n')
    f.write('    unittest.main()\n')
print("Done!")
