path = '/Users/suavemax27/scoutcloud/scoutcloud.dev/src/functions/photo-tagger/handler.py'
with open(path, 'w') as f:
    f.write('#!/usr/bin/env python3\n')
    f.write('import boto3, json, logging, os\n')
    f.write('from datetime import datetime\n\n')
    f.write('logger = logging.getLogger()\n')
    f.write('logger.setLevel(logging.INFO)\n\n')
    f.write('def get_rekognition_client():\n')
    f.write('    return boto3.client("rekognition", region_name="us-east-1")\n\n')
    f.write('def get_dynamodb_resource():\n')
    f.write('    return boto3.resource("dynamodb", region_name="us-east-1")\n\n')
    f.write('def analyze_photo(s3_bucket, s3_key, rekognition=None):\n')
    f.write('    if rekognition is None:\n')
    f.write('        rekognition = get_rekognition_client()\n')
    f.write('    label_response = rekognition.detect_labels(\n')
    f.write('        Image={"S3Object": {"Bucket": s3_bucket, "Name": s3_key}},\n')
    f.write('        MaxLabels=10,\n')
    f.write('        MinConfidence=80.0,\n')
    f.write('    )\n')
    f.write('    face_response = rekognition.detect_faces(\n')
    f.write('        Image={"S3Object": {"Bucket": s3_bucket, "Name": s3_key}},\n')
    f.write('        Attributes=["DEFAULT"],\n')
    f.write('    )\n')
    f.write('    labels = [\n')
    f.write('        {"name": label["Name"], "confidence": round(label["Confidence"], 2)}\n')
    f.write('        for label in label_response["Labels"]\n')
    f.write('    ]\n')
    f.write('    return {\n')
    f.write('        "labels": labels,\n')
    f.write('        "face_count": len(face_response["FaceDetails"]),\n')
    f.write('        "is_basketball_photo": any(\n')
    f.write('            label["name"] in ["Basketball", "Sports", "Person", "Ball"]\n')
    f.write('            for label in labels\n')
    f.write('        ),\n')
    f.write('    }\n\n')
    f.write('def store_results(photo_key, analysis, dynamodb=None):\n')
    f.write('    if dynamodb is None:\n')
    f.write('        dynamodb = get_dynamodb_resource()\n')
    f.write('    table = dynamodb.Table("scoutcloud-photo-tags")\n')
    f.write('    table.put_item(Item={\n')
    f.write('        "photo_key":    photo_key,\n')
    f.write('        "analyzed_at":  datetime.utcnow().isoformat(),\n')
    f.write('        "labels":       analysis["labels"],\n')
    f.write('        "face_count":   analysis["face_count"],\n')
    f.write('        "is_basketball": analysis["is_basketball_photo"],\n')
    f.write('    })\n\n')
    f.write('def lambda_handler(event, context, rekognition=None, dynamodb=None):\n')
    f.write('    processed = 0\n')
    f.write('    for record in event["Records"]:\n')
    f.write('        s3_bucket = record["s3"]["bucket"]["name"]\n')
    f.write('        s3_key    = record["s3"]["object"]["key"]\n')
    f.write('        if not s3_key.startswith("players/photos/"):\n')
    f.write('            logger.info(f"Skipping non-photo file: {s3_key}")\n')
    f.write('            continue\n')
    f.write('        logger.info(json.dumps({\n')
    f.write('            "event": "photo_analysis_started",\n')
    f.write('            "bucket": s3_bucket,\n')
    f.write('            "key": s3_key,\n')
    f.write('        }))\n')
    f.write('        analysis = analyze_photo(s3_bucket, s3_key, rekognition)\n')
    f.write('        store_results(s3_key, analysis, dynamodb)\n')
    f.write('        logger.info(json.dumps({\n')
    f.write('            "event": "photo_analysis_complete",\n')
    f.write('            "key": s3_key,\n')
    f.write('            "labels": [l["name"] for l in analysis["labels"]],\n')
    f.write('            "faces": analysis["face_count"],\n')
    f.write('        }))\n')
    f.write('        processed += 1\n')
    f.write('    return {"processed": processed}\n')
print("Done!")
