path = '/Users/suavemax27/scoutcloud/scoutcloud.dev/src/functions/cost-report/handler.py'
with open(path, 'w') as f:
    f.write('#!/usr/bin/env python3\n')
    f.write('import boto3, json, logging, os, urllib.request\n')
    f.write('from datetime import datetime, timedelta\n\n')
    f.write('logger = logging.getLogger()\n')
    f.write('logger.setLevel(logging.INFO)\n\n')
    f.write('def get_cost_by_environment(start_date, end_date):\n')
    f.write('    ce = boto3.client("ce", region_name="us-east-1")\n')
    f.write('    response = ce.get_cost_and_usage(\n')
    f.write('        TimePeriod={"Start": start_date, "End": end_date},\n')
    f.write('        Granularity="MONTHLY",\n')
    f.write('        Metrics=["UnblendedCost"],\n')
    f.write('        GroupBy=[{"Type": "TAG", "Key": "Environment"}],\n')
    f.write('    )\n')
    f.write('    results = {}\n')
    f.write('    for result in response["ResultsByTime"]:\n')
    f.write('        for group in result["Groups"]:\n')
    f.write('            env = group["Keys"][0].replace("Environment$", "") or "untagged"\n')
    f.write('            cost = float(group["Metrics"]["UnblendedCost"]["Amount"])\n')
    f.write('            results[env] = results.get(env, 0) + cost\n')
    f.write('    return results\n\n')
    f.write('def get_total_cost(start_date, end_date):\n')
    f.write('    ce = boto3.client("ce", region_name="us-east-1")\n')
    f.write('    response = ce.get_cost_and_usage(\n')
    f.write('        TimePeriod={"Start": start_date, "End": end_date},\n')
    f.write('        Granularity="MONTHLY",\n')
    f.write('        Metrics=["UnblendedCost"],\n')
    f.write('    )\n')
    f.write('    total = sum(\n')
    f.write('        float(r["Total"]["UnblendedCost"]["Amount"])\n')
    f.write('        for r in response["ResultsByTime"]\n')
    f.write('    )\n')
    f.write('    return total\n\n')
    f.write('def format_slack_message(costs, total, start_date, end_date):\n')
    f.write('    lines = [\n')
    f.write('        f"*ScoutCloud Weekly Cost Report*",\n')
    f.write('        f"_{start_date} to {end_date}_",\n')
    f.write('        "",\n')
    f.write('        "*Cost by Environment:*",\n')
    f.write('    ]\n')
    f.write('    for env, cost in sorted(costs.items(), key=lambda x: x[1], reverse=True):\n')
    f.write('        bar = "=" * int(cost / total * 20) if total > 0 else ""\n')
    f.write('        lines.append(f"  {env:<12} ${cost:.2f}  {bar}")\n')
    f.write('    lines.append("")\n')
    f.write('    lines.append(f"*Total: ${total:.2f}*")\n')
    f.write('    if total > 40:\n')
    f.write('        lines.append(":warning: Approaching $50 monthly budget!")\n')
    f.write('    return {"text": chr(10).join(lines)}\n\n')
    f.write('def post_to_slack(message, webhook_url):\n')
    f.write('    data = json.dumps(message).encode("utf-8")\n')
    f.write('    req = urllib.request.Request(\n')
    f.write('        webhook_url,\n')
    f.write('        data=data,\n')
    f.write('        headers={"Content-Type": "application/json"},\n')
    f.write('        method="POST",\n')
    f.write('    )\n')
    f.write('    with urllib.request.urlopen(req) as response:\n')
    f.write('        return response.status\n\n')
    f.write('def lambda_handler(event, context):\n')
    f.write('    end_date = datetime.utcnow().strftime("%Y-%m-%d")\n')
    f.write('    start_date = (datetime.utcnow() - timedelta(days=7)).strftime("%Y-%m-%d")\n\n')
    f.write('    costs = get_cost_by_environment(start_date, end_date)\n')
    f.write('    total = get_total_cost(start_date, end_date)\n')
    f.write('    message = format_slack_message(costs, total, start_date, end_date)\n\n')
    f.write('    webhook_url = os.environ.get("SLACK_WEBHOOK_URL", "")\n')
    f.write('    if webhook_url:\n')
    f.write('        status = post_to_slack(message, webhook_url)\n')
    f.write('        logger.info(json.dumps({"event": "slack_posted", "status": status}))\n')
    f.write('    else:\n')
    f.write('        logger.info(json.dumps({"event": "cost_report", "message": message["text"]}))\n\n')
    f.write('    logger.info(json.dumps({\n')
    f.write('        "event": "cost_report_complete",\n')
    f.write('        "period": f"{start_date} to {end_date}",\n')
    f.write('        "total": round(total, 2),\n')
    f.write('        "by_environment": {k: round(v, 2) for k, v in costs.items()},\n')
    f.write('    }))\n\n')
    f.write('    return {"total": round(total, 2), "by_environment": {k: round(v, 2) for k, v in costs.items()}}\n')
print("Done!")
